# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b558d0a448d4ff73c06da7c815e4541ef7b3e1e8b1fca5032afc7e2f02e9a96fe4d334e02977c1bd86c117f57cdd715e8d7af7c34965ae0384fa78ebc6e58fb7

test:
  secret_key_base: dbd97afa109b1b38d706ca0fd97c816556bb6c1acffce1e39420eb2cadb482b36a0ec591e7891c72a9e0ba213493191c76b08c03cb84c74e959dd853ac32d40b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
